/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.akhdanaudi.sobat.views;

import com.akhdanaudi.sobat.controllers.ViewController;
import java.awt.CardLayout;
import java.awt.Container;

/**
 *
 * @author akhda
 */
public class MenuView extends javax.swing.JPanel {
    ViewController controller;

    /**
     * Creates new form HomeView
     * @param controller
     */
    public MenuView(ViewController controller) {
        initComponents();
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        menu_items = new javax.swing.JPanel();
        menu_obat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menu_penjual = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menu_laporan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        setLayout(new java.awt.GridLayout(2, 0));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SOBAT");
        jPanel5.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistem Informasi Obat");
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Akhdan Musyaffa Firdaus & Zulfa Dwi Audina");
        jPanel5.add(jLabel9, java.awt.BorderLayout.PAGE_END);

        add(jPanel5);

        menu_items.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        menu_obat.setBackground(new java.awt.Color(255, 255, 255));
        menu_obat.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        menu_obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_obatMouseClicked(evt);
            }
        });
        menu_obat.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("20");
        menu_obat.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Obat");
        menu_obat.add(jLabel1, java.awt.BorderLayout.CENTER);

        menu_items.add(menu_obat);

        menu_penjual.setBackground(new java.awt.Color(255, 255, 255));
        menu_penjual.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        menu_penjual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_penjualMouseClicked(evt);
            }
        });
        menu_penjual.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("20");
        menu_penjual.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Penjualan");
        menu_penjual.add(jLabel8, java.awt.BorderLayout.CENTER);

        menu_items.add(menu_penjual);

        menu_laporan.setBackground(new java.awt.Color(255, 255, 255));
        menu_laporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        menu_laporan.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("20");
        menu_laporan.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jLabel3.setText("Laporan Penjualan");
        menu_laporan.add(jLabel3, java.awt.BorderLayout.CENTER);

        menu_items.add(menu_laporan);

        add(menu_items);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_obatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_obatMouseClicked
        controller.changeView("Menu Obat");
    }//GEN-LAST:event_menu_obatMouseClicked

    private void menu_penjualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_penjualMouseClicked
        controller.changeView("Menu Penjualan");
    }//GEN-LAST:event_menu_penjualMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel menu_items;
    private javax.swing.JPanel menu_laporan;
    private javax.swing.JPanel menu_obat;
    private javax.swing.JPanel menu_penjual;
    // End of variables declaration//GEN-END:variables
}
