/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.akhdanaudi.sobat.views;

import com.akhdanaudi.sobat.controllers.ObatController;
import com.akhdanaudi.sobat.controllers.ViewController;
import com.akhdanaudi.sobat.models.JenisObat;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author akhda
 */
public class ObatView extends javax.swing.JPanel {
    ViewController viewController;
    ObatController controller;
    private List<JenisObat> listJenis;
    /**
     * Creates new form ObatView
     * @param viewController
     * @param controller
     */
    public ObatView(ViewController viewController, ObatController controller) {
        initComponents();
        this.viewController = viewController;
        this.controller = controller;
        
        stok_obat_field.setValue((int) 0);
        tabelObat.setModel(this.controller.getTableModel());
        delete_btn.setVisible(false);
        
        //Load combobox dummy
        initCombobox();
        
        tabelObat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!tabelObat.getSelectionModel().isSelectionEmpty()) {
                    int baris = tabelObat.getSelectedRow();
                    id_obat_field.setText(tabelObat.getValueAt(baris, 0).toString());
                    kode_obat_field.setText(tabelObat.getValueAt(baris, 1).toString());
                    nama_obat_field.setText(tabelObat.getValueAt(baris, 2).toString());
                    
                    String cariJenis = tabelObat.getValueAt(baris, 3).toString();
                    JenisObat jenis = listJenis.stream()
                            .filter(item -> cariJenis.equals(item.getNamaJenis()))
                            .findAny()
                            .orElse(null);
                    jenis_obat_id_cmb.setSelectedIndex(jenis.getJenisId());
                    
                    harga_obat_field.setText(tabelObat.getValueAt(baris, 4).toString());
                    stok_obat_field.setValue((int) tabelObat.getValueAt(baris, 5));
                    delete_btn.setVisible(true);
                    save_btn.setText("Update");
                } else {
                    delete_btn.setVisible(false);
                    save_btn.setText("Simpan");
                }
            }
        });
    }
    
    private void initCombobox(){
        listJenis = controller.getJenisObat();
        jenis_obat_id_cmb.addItem("Pilih Jenis");
        for (JenisObat jenis : listJenis) {
            jenis_obat_id_cmb.addItem(jenis.getNamaJenis());
        }
    }
    
    private void resetForm() {
        id_obat_field.setText("");
        kode_obat_field.setText("");
        nama_obat_field.setText("");
        jenis_obat_id_cmb.setSelectedIndex(0);
        harga_obat_field.setText("");
        stok_obat_field.setValue((int) 0);
        tabelObat.getSelectionModel().clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        id_obat_field = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kode_obat_field = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nama_obat_field = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jenis_obat_id_cmb = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        harga_obat_field = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        stok_obat_field = new javax.swing.JSpinner();
        button = new javax.swing.JPanel();
        delete_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelObat = new javax.swing.JTable();

        setLayout(new java.awt.GridLayout(2, 0));

        atas.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        atas.setLayout(new java.awt.GridLayout(1, 2));

        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        backButton.setText("Kembali");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);

        jPanel8.add(jPanel1);

        jLabel2.setText("List Obat yang Tersedia");
        jPanel2.add(jLabel2);

        jPanel8.add(jPanel2);

        atas.add(jPanel8);

        form.setLayout(new java.awt.GridLayout(7, 0));

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel7.setText("Id");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel10.add(jLabel7);

        id_obat_field.setEditable(false);
        id_obat_field.setMinimumSize(new java.awt.Dimension(20, 20));
        id_obat_field.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel10.add(id_obat_field);

        form.add(jPanel10);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel3.setText("Kode");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel3.add(jLabel3);

        kode_obat_field.setMinimumSize(new java.awt.Dimension(20, 20));
        kode_obat_field.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel3.add(kode_obat_field);

        form.add(jPanel3);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel5.setText("Nama");
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel5.add(jLabel5);

        nama_obat_field.setMinimumSize(new java.awt.Dimension(20, 20));
        nama_obat_field.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel5.add(nama_obat_field);

        form.add(jPanel5);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel4.setText("Jenis");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel4.add(jLabel4);

        jenis_obat_id_cmb.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel4.add(jenis_obat_id_cmb);

        form.add(jPanel4);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel1.setText("Harga");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel6.add(jLabel1);

        harga_obat_field.setMinimumSize(new java.awt.Dimension(20, 20));
        harga_obat_field.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel6.add(harga_obat_field);

        form.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel6.setText("Stok");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel7.add(jLabel6);

        stok_obat_field.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel7.add(stok_obat_field);

        form.add(jPanel7);

        button.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        button.add(delete_btn);

        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        button.add(reset_btn);

        save_btn.setText("Simpan");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        button.add(save_btn);

        form.add(button);

        atas.add(form);

        add(atas);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        jPanel9.setLayout(new java.awt.CardLayout());

        tabelObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelObat);

        jPanel9.add(jScrollPane1, "card2");

        add(jPanel9);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        viewController.changeView("Menu Utama");
    }//GEN-LAST:event_backButtonActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        resetForm();
    }//GEN-LAST:event_reset_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        String kode = kode_obat_field.getText();
        String nama = nama_obat_field.getText();
        String jenis = String.valueOf(jenis_obat_id_cmb.getSelectedIndex());
        String harga = harga_obat_field.getText();
        int stok = (int) stok_obat_field.getValue();
        tabelObat.getSelectionModel().clearSelection();
        ArrayList<String>  res = controller.validateInput(kode, nama, jenis, harga, stok);
        if (res.size() > 0) {
            String concatMessages = res.stream().reduce("", (prev, next) -> prev + "\n" + next);
            JOptionPane.showMessageDialog(this, concatMessages);
        } else {
            try {
                if (id_obat_field.getText().isEmpty()) {
                    controller.saveToDatabase(
                        kode, 
                        nama, 
                        Integer.parseInt(jenis), 
                        Integer.parseInt(harga),
                        stok
                    );
                    JOptionPane.showMessageDialog(this, "Sukses Menyimpan Data!");
                    resetForm();
                } else {
                    int id = Integer.parseInt(id_obat_field.getText());
                    controller.updateFromDatabase(
                        kode, 
                        nama, 
                        Integer.parseInt(jenis), 
                        Integer.parseInt(harga),
                        stok,
                        id
                    );
                    JOptionPane.showMessageDialog(this, "Sukses Mengupdate Data " + kode + "!");
                }
                controller.getTableModel().setRowCount(0);
                controller.loadTableData();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data " + e.toString());
            }
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        try {
            controller.deleteFromDatabase(Integer.parseInt(id_obat_field.getText()));
            JOptionPane.showMessageDialog(this, "Sukses Menghapus Obat " + nama_obat_field.getText() + "!");
            controller.getTableModel().setRowCount(0);
            controller.loadTableData();
            resetForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data " + e.toString());
        }
    }//GEN-LAST:event_delete_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atas;
    private javax.swing.JToggleButton backButton;
    private javax.swing.JPanel button;
    private javax.swing.JButton delete_btn;
    private javax.swing.JPanel form;
    private javax.swing.JTextField harga_obat_field;
    private javax.swing.JTextField id_obat_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis_obat_id_cmb;
    private javax.swing.JTextField kode_obat_field;
    private javax.swing.JTextField nama_obat_field;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JSpinner stok_obat_field;
    private javax.swing.JTable tabelObat;
    // End of variables declaration//GEN-END:variables
}
