/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.akhdanaudi.sobat.views;

import com.akhdanaudi.sobat.controllers.ViewController;

/**
 *
 * @author akhda
 */
public class PenjualanView extends javax.swing.JPanel {
    ViewController controller;

    /**
     * Creates new form ObatView
     * @param controller
     */
    public PenjualanView(ViewController controller) {
        initComponents();
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kode_obat = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nama_obat = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jenis_obat_id = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        harga_obat = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        stok_obat = new javax.swing.JSpinner();
        button = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.GridLayout(2, 0));

        atas.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        atas.setLayout(new java.awt.GridLayout(1, 2));

        form.setLayout(new java.awt.GridLayout(6, 0));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel3.setText("Kode");
        jLabel3.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel3.add(jLabel3);

        kode_obat.setMinimumSize(new java.awt.Dimension(20, 20));
        kode_obat.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel3.add(kode_obat);

        form.add(jPanel3);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel5.setText("Nama");
        jLabel5.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel5.add(jLabel5);

        nama_obat.setMinimumSize(new java.awt.Dimension(20, 20));
        nama_obat.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel5.add(nama_obat);

        form.add(jPanel5);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel4.setText("Jenis");
        jLabel4.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel4.add(jLabel4);

        jenis_obat_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jenis_obat_id.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel4.add(jenis_obat_id);

        form.add(jPanel4);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel1.setText("Harga");
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel6.add(jLabel1);

        harga_obat.setMinimumSize(new java.awt.Dimension(20, 20));
        harga_obat.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel6.add(harga_obat);

        form.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel6.setText("Stok");
        jLabel6.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel7.add(jLabel6);

        stok_obat.setPreferredSize(new java.awt.Dimension(240, 20));
        jPanel7.add(stok_obat);

        form.add(jPanel7);

        button.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton1.setText("Reset");
        button.add(jButton1);

        jButton2.setText("Simpan");
        button.add(jButton2);

        form.add(button);

        atas.add(form);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Penjualan");
        jPanel8.add(jLabel2, new java.awt.GridBagConstraints());

        atas.add(jPanel8);

        add(atas);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atas;
    private javax.swing.JPanel button;
    private javax.swing.JPanel form;
    private javax.swing.JTextField harga_obat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jenis_obat_id;
    private javax.swing.JTextField kode_obat;
    private javax.swing.JTextField nama_obat;
    private javax.swing.JSpinner stok_obat;
    // End of variables declaration//GEN-END:variables
}
